<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PaymentGateway.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Entity Framework Core: nosso ORM (mapeia classes C# para tabelas SQL) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <!-- .Design é usado só na hora de gerar Migrations, não em tempo de execução -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!-- Cliente oficial do RabbitMQ pra .NET -->
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <!-- Necessário para o services.Configure<T>(IConfigurationSection) funcionar -->
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentGateway.Application\PaymentGateway.Application.csproj" />
  </ItemGroup>

</Project>
